
8:
	cat /home/calvario/hombre.txt | java -jar proyecto1.jar -r -o /home/calvario/elemplo.txt

7:
	cat /home/calvario/hombre.txt | java -jar proyecto1.jar -o /home/calvario/elemplo.txt

6:
	cat /home/calvario/hombre.txt | java -jar proyecto1.jar -r

5:
	cat /home/calvario/hombre.txt | java -jar proyecto1.jar

4:
	java -jar proyecto1.jar /home/calvario/hombre.txt -r -o /home/calvario/elemplo.txt

3:
	java -jar proyecto1.jar /home/calvario/hombre.txt -o /home/calvario/elemplo.txt

2:
	java -jar proyecto1.jar -r /home/calvario/hombre.txt

1:
	java -jar proyecto1.jar /home/calvario/hombre.txt